name: "Comprobar errores de formato Markdown"
on:
  push:
    paths:
      - "**/*.md"
      - "*.md"

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out fuentes
        uses: actions/checkout@v4
      - name: "Comprueba errores de formato Markdown"
        uses: articulate/actions-markdownlint@v1
      - uses: rojopolis/spellcheck-github-actions@v0
        name: "Comprueba ortograf√≠a"
        with:
          source_files: "README.md docs/*.md"
