name: "Comprobaciones b√°sicas del cuerpo del PR"
on:
  push:
    paths: '**/*.md'
  pull_request:
    paths: '**/*.md'

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Lint changelog file
        uses: avto-dev/markdown-lint@v1
        with:
          args: './README.md'
